Version check
lysanderp41/CodeUSummer2017 pull request #7
Opened 2017-05-29 16:02 UTC by mlk209

fixed the serverInfo

2017-05-30 02:47 UTC, lysanderp41 requested changes

2017-05-30 02:47 UTC, lysanderp41 commented on src/codeu/chat/client/commandline/Chat.java
> +        System.out.println("  Display the version of the server.");
Maybe add an indent in the print statement so that it aligns with the other options in the menu

2017-05-30 02:47 UTC, lysanderp41 commented on src/codeu/chat/client/commandline/Chat.java
> +    panel.register("info", new Panel.Command() {
Change the "info" command to something like "version" or "server-version" to make it more clear as to what the command will return.

2017-05-30 02:47 UTC, lysanderp41 commented on src/codeu/chat/client/core/View.java
> +    try(final Connection connection = this.source.connect()){
Add a space between `try` and the parenthesis to maintain consistent styling

2017-05-30 02:47 UTC, lysanderp41 commented on src/codeu/chat/client/commandline/Chat.java
> +        System.out.println("  Display the version of the server.");
Also put the "version check" command above the "exit" command to keep the menu easy to read

2017-05-30 02:47 UTC, lysanderp41 commented on src/codeu/chat/client/core/View.java
> +    try(final Connection connection = this.source.connect()){
You should change the name of the function to something like `getVersion()` to make it more descriptive for anyone reading the code

2017-05-30 02:47 UTC, lysanderp41 commented on src/codeu/chat/common/NetworkCode.java
> +      SERVER_INFO_RESPONSE = 34;
It would be a good idea to change `SERVER_INFO_REQUEST` and `SERVER_INFO_RESPONSE` to something more descriptive like `SERVER_VERSION_REQUEST`.

2017-05-30 03:38 UTC, joecarnahan reviewed
I just wanted to leave a meta-comment that it's cool to see code review going on here. 👍

2017-06-02 15:28 UTC, mlk209 commented on src/codeu/chat/client/commandline/Chat.java
> +        System.out.println("  Display the version of the server.");
Updated the styling by adding the indent and also put the command before the exit command

2017-06-02 15:29 UTC, mlk209 commented on src/codeu/chat/client/commandline/Chat.java
> +    panel.register("info", new Panel.Command() {
changed "info" to "version"

2017-06-02 15:34 UTC, mlk209 commented on src/codeu/chat/client/core/View.java
> +    try(final Connection connection = this.source.connect()){
Styling is now consistent

2017-06-02 15:34 UTC, mlk209 commented on src/codeu/chat/client/core/View.java
> +    try(final Connection connection = this.source.connect()){
changed the name of the function to be getVersion()!

2017-06-02 15:37 UTC, mlk209 commented on src/codeu/chat/common/NetworkCode.java
> +      SERVER_INFO_RESPONSE = 34;
changed SERVER_INFO_REQUEST and SERVER_INFO_RESPONSE to SERVER_VERSION_REQUEST!

2017-06-02 21:28 UTC, lysanderp41 approved these changes
LGTM!

2017-06-02 21:28 UTC, lysanderp41 commented on src/codeu/chat/client/commandline/Chat.java
> +        System.out.println("  Display the version of the server.");
It might look a little cleaner with the exit command on the bottom and a slight indentation that lines up with the rest of the descriptions for `System.out.println("  Display the version of the server.");`.

2017-06-04 21:04 UTC, merged